import Head from 'next/head'
import Image from 'next/image'
import { Inter, Stick } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from "framer-motion"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Blooming Aqua</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-neutral-50'>
      <video className='h-screen w-full object-cover' autoPlay loop muted>
        <source src='/hd_water.mp4' type='video/mp4' />
      </video>
      <div className='absolute w-full h-screen top-0 pt-[10vh] text-[14rem] uppercase text-neutral-100 leading-none opacity-90 backdrop-blur'>
        <div>
        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{stiffness: 50, duration: 0.7}}>
          <div className='ml-[-4vw]'>Blooming</div>
          <div className='ml-[50vw]'>Aqua</div>
          </motion.div>
        </div>
      </div>
      <div className='px-10 mt-10 grid grid-cols-2'>
      <motion.div 
          initial={{ x: -100 }}
          whileInView={{ x: 0 }}
          transition={{stiffness: 50, duration: 0.7}}>
        <div className='text-8xl mb-5 w-2/3'>BLOOMING AQUA</div>
        </motion.div>
        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{stiffness: 50, duration: 0.7}}>
      <div className='mb-10'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ligula magna, viverra vel orci non, lacinia aliquet nisi. Cras nec congue sapien. Etiam vitae sodales sapien. Ut gravida sem non nibh feugiat cursus. Pellentesque sit amet magna in diam pellentesque congue. Fusce eu dictum erat. Sed faucibus pretium suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam varius lacinia faucibus. Morbi finibus sem ut neque luctus, nec rhoncus ante finibus. Nam in sem non felis laoreet condimentum. Curabitur hendrerit ligula vitae magna efficitur, sit amet fermentum risus malesuada. Curabitur ut sagittis tellus, sit amet auctor justo. Nam eget nisi bibendum, sollicitudin ex eget, lobortis urna. Nunc placerat nisl ac leo rutrum pretium.
      <br/><br/>
Nam laoreet, tortor et venenatis pharetra, erat tellus auctor massa, sed rutrum dui elit sit amet arcu. Maecenas interdum sodales lectus. Ut ut lobortis mi, et dictum augue. Morbi diam lectus, vestibulum at vehicula nec, tempus sit amet nibh. In porttitor est non leo laoreet tempor. Vestibulum ac imperdiet ligula, ac ultrices lacus. Aliquam vulputate justo et ante viverra mollis. Maecenas commodo, arcu vel sagittis commodo, mauris enim auctor est, quis finibus augue lacus id quam. Morbi lacus urna, elementum tempus diam ut, faucibus pulvinar orci. Praesent et dapibus enim, tempor accumsan ligula.
<br/><br/>
Duis eros neque, pellentesque vitae aliquet in, viverra at quam. Cras tellus mauris, tristique interdum suscipit eu, aliquam non tortor. Duis euismod sem at egestas ornare. Morbi tristique tortor massa, eget finibus enim interdum a. Aenean feugiat lectus eros, sed lobortis purus accumsan quis. Cras quis orci libero. Nullam vel eros non libero tincidunt dictum. Cras rutrum eros id arcu euismod tempor. Nullam ornare vitae augue id dignissim. Nullam finibus lacus ut porta malesuada. Phasellus molestie finibus orci lobortis placerat. Vivamus augue dui, fermentum dapibus dui eget, consequat sagittis magna. Nulla blandit aliquet feugiat. Ut porttitor odio vitae ullamcorper aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec molestie felis quam, eu eleifend libero eleifend id.
</div>
      </motion.div>
      </div>
      </main>
    </>
  )
}
